# Generated by Django 5.2.12 on 2026-04-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_scrape_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='reading_count',
            field=models.IntegerField(default=0),
        ),
    ]
