# Generated by Django 5.2.10 on 2026-05-02 11:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_default_counts"),
        ("learning_paths", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic_input", models.CharField(blank=True, max_length=255)),
                ("additional_context", models.TextField(blank=True, default="")),
                (
                    "relevance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Cosine similarity score dari FAISS (0.0–1.0)",
                    ),
                ),
                (
                    "ai_explanation",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Penjelasan AI kenapa course ini cocok untuk user",
                    ),
                ),
                (
                    "is_saved",
                    models.BooleanField(
                        default=False,
                        help_text="User menandai ingin menyimpan course ini",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations_received",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "course_recommendations",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course", "topic_input"),
                        name="uniq_user_course_topic",
                    )
                ],
            },
        ),
    ]
