# Generated by Django 5.2.10 on 2026-05-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning_paths", "0002_add_course_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserecommendation",
            name="regenerate_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Jumlah kali user regenerate rekomendasi ini"
            ),
        ),
    ]
