# Generated by Django 5.2.10 on 2026-05-02 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_default_counts"),
        ("learning_paths", "0003_add_regenerate_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningpath",
            name="regenerate_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Additional context used in last regenerate",
            ),
        ),
        migrations.AddField(
            model_name="learningpath",
            name="regenerate_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="learningpathcourse",
            name="regenerate_version",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="LearningPath.regenerate_count at time this course was added",
            ),
        ),
        migrations.AddField(
            model_name="learningpathcourse",
            name="replaced_by",
            field=models.ForeignKey(
                blank=True,
                help_text="If this course was replaced, reference the new course here",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replaced_courses",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="learningpathcourse",
            name="replacement_context",
            field=models.TextField(
                blank=True,
                default="",
                help_text="AI context used to find replacement course",
            ),
        ),
        migrations.AddField(
            model_name="learningpathcourse",
            name="replacement_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="User-provided reason for replacing this course",
            ),
        ),
    ]
