# Generated by Django 5.2.12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('age_range', models.CharField(blank=True, choices=[('18-24', '18-24'), ('25-34', '25-34'), ('35+', '35+')], max_length=10)),
                ('education_level', models.CharField(blank=True, choices=[('SMA', 'SMA'), ('D3', 'D3'), ('S1', 'S1'), ('S2', 'S2')], max_length=10)),
                ('operating_system', models.CharField(blank=True, choices=[('windows', 'windows'), ('macos', 'macos'), ('linux', 'linux')], max_length=10)),
                ('git_skill', models.CharField(blank=True, choices=[('none', 'none'), ('basic', 'basic'), ('intermediate', 'intermediate')], max_length=20)),
                ('cli_level', models.SmallIntegerField(blank=True, null=True)),
                ('logic_level', models.SmallIntegerField(blank=True, null=True)),
                ('weekly_hours', models.CharField(blank=True, choices=[('<4', '<4'), ('4-8', '4-8'), ('8-14', '8-14'), ('15+', '15+')], max_length=10)),
                ('study_slot', models.CharField(blank=True, choices=[('pagi', 'pagi'), ('malam', 'malam'), ('kerja', 'kerja'), ('weekend', 'weekend')], max_length=10)),
                ('material_format', models.CharField(blank=True, choices=[('video', 'video'), ('text', 'text'), ('interactive', 'interactive'), ('project', 'project')], max_length=15)),
                ('theory_practice', models.CharField(blank=True, choices=[('theory', 'theory'), ('balanced', 'balanced'), ('practice', 'practice')], max_length=10)),
                ('evaluation_type', models.CharField(blank=True, choices=[('quiz', 'quiz'), ('coding_challenge', 'coding_challenge'), ('project', 'project')], max_length=20)),
                ('target_role', models.CharField(blank=True, choices=[('backend', 'backend'), ('devops', 'devops'), ('data_ml', 'data_ml')], max_length=30)),
                ('main_goal', models.CharField(blank=True, choices=[('career_change', 'career_change'), ('upskilling', 'upskilling'), ('hobby', 'hobby')], max_length=20)),
                ('ram_gb', models.CharField(blank=True, choices=[('<8', '<8'), ('8-16', '8-16'), ('16+', '16+')], max_length=10)),
                ('internet_quality', models.CharField(blank=True, choices=[('unstable', 'unstable'), ('stable', 'stable'), ('very_stable', 'very_stable')], max_length=15)),
                ('budget_idr', models.CharField(blank=True, choices=[('<500k', '<500k'), ('500k-2m', '500k-2m'), ('>2m', '>2m')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.user')),
            ],
            options={
                'db_table': 'users_preferences',
            },
        ),
    ]
