# Generated by Django 5.2.12 on 2026-04-04 15:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('section', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('input_type', models.CharField(blank=True, max_length=64)),
                ('options_json', models.JSONField()),
                ('variable_key', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order_number'],
            },
        ),
    ]
