# Generated by Django 5.2.12 on 2026-04-04 15:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionnaireAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_option', models.CharField(max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='questionnaires.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_questionnaire_answers',
                'ordering': ['question__order_number'],
                'constraints': [models.UniqueConstraint(fields=('user', 'question'), name='uniq_user_questionnaire_answer')],
            },
        ),
    ]
